[settings]
timeout = 1000

[relaychain.genesis.runtime.runtime_genesis_config.configuration.config]
  max_validators_per_core = 5
  needed_approvals = 2

# cannot be changed after the first block got produced
[relaychain.genesis.runtime]
session_length_in_block = 3

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
chain_spec_command = "polkadot build-spec --chain rococo-local --disable-default-bootnode"
default_command = "polkadot"

[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lparachain=debug,runtime=debug,grandpa=trace" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lparachain=debug,runtime=debug,grandpa=trace"]

  [[relaychain.nodes]]
  name = "charlie"
  args = [ "--charlie", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  args = [ "--dave", "-lparachain=debug,runtime=debug,grandpa=trace"]

  [[relaychain.nodes]]
  name = "ferdie"
  args = [ "--ferdie", "-lparachain=debug,runtime=debug,grandpa=trace" ]

  [[relaychain.nodes]]
  name = "eve"
  args = [ "--eve", "-lparachain=debug,runtime=debug,grandpa=trace"]

  [[relaychain.nodes]]
  name = "one"
  args = [ "--one", "-lparachain=debug,runtime=debug,grandpa=trace" ]

  [[relaychain.nodes]]
  name = "two"
  args = [ "--two", "-lparachain=debug,runtime=debug,grandpa=trace"]


# Zer0 parachains
#[[parachains]]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
